### ISSUE TITLE
account.move 

### ISSUE THREAD

**Issue by phamthuha0970** [er-harsh-dhaduk/odoo-training#1]
I want to ask more about account.move 
I I'm building a project about invoices. How to save amount items in bill?

**Comment by er-harsh-dhaduk** [comment]
Hi @phamthuha0970 
You can add in invoice line field here there are many fields available like qty, price, product, uom, taxes.

if you are trying to add from backend side. Please check special command specially 6,0
https://www.youtube.com/playlist?list=PLAR8TpPnVeTT-PW34zfEmX4Ji6xE77H9T

Second way is from frontend you can directly add those information from that form view.
